### PR TITLE
Fix  two symbol issues

### PR DESCRIPTION
**Pull request by chenshanpei**
1. fix local symbol postion assert error
2. remove GCC optimized functions from 'undefined' function set

### CODE REVIEW

**Comment by dtcccc** [comment]
Will simply removing assert cause other bugs? @ampresent

**Comment by ampresent** [comment]
> Will simply removing assert cause other bugs? @ampresent

I think what this PR does, is making

```c
local_sympos[(key, file)] = fn_pos[the_last_appearance_of_key_file]
```
, which makes some sense. And I can't think of what potential bugs there might be, for now.

So I think it's acceptable.

**Comment by ampresent** [comment]
All LGTM

**Pull request merged**
