### PR TITLE
config: add Anolis Cloud Kernel 5.10 config

### PR DESCRIPTION
**Pull request by Dengerwei**
This patch adds the config of Anolis Cloud Kernel 5.10 and tested in Alibaba Cloud Linux 3 system. And now this is an initial boundary of this config which will be adjusted later.

### CODE REVIEW

**Comment by ampresent** [comment]
Explain why we need to add a `no_inline` to prepare_task_switch. Others LGTM

**Comment by Dengerwei** [comment]
> Explain why we need to add a `no_inline` to prepare_task_switch. Others LGTM

I have updated the log in dynamic_springboard.patch.

**Comment by ampresent** [comment]
LGTM

**Pull request merged**
